micronaut:
  application:
    name: ${project.artifactId}
  server:
    port: 8070
endpoints:
  all:
    port: 8090
  health:
    enabled: true

trust:
  lists:
    - refreshSeconds: 5
      url: "https://tl.bundesnetzagentur.de/TL-DE.XML"
  stores:
    - path: "store.jks"
      type: "JKS"
      password: "password"

---
logger:
  levels:
    ROOT: INFO